lang:
  per-player: true # Get player language and set messages
  default-lang: "en_US" # if player lang isn't found

# Nitrite - File storage (not for large scale)
# Mongodb - For large scale
database: "nitrite"

nitrite:
  user: "nitrite"
  password: "mypass"

# Click types:
# DOUBLE_CLICK, DROP, LEFT, MIDDLE, NUMBER_KEY, RIGHT, SHIFT_LEFT, SHIFT_RIGHT, SWAP_OFFHAND, etc
# Check all in https://hub.spigotmc.org/javadocs/spigot/org/bukkit/event/inventory/ClickType.html
#
# Action:
# SELL, GIVE, GIVE_HALF and GIVE_ALL
spawner-click:
  LEFT: "GIVE,3" # Give:Amount
  RIGHT: "GIVE_HALF"
  MIDDLE: "GIVE_ALL"
  DROP: "SELL"

# Action:
# LEVEL, LEVEL_HALF and LEVEL_MAX
upgrader-click:
  LEFT: "LEVEL,1" # Increase:Amount
  RIGHT: "LEVEL_HALF"
  MIDDLE: "LEVEL_MAX"